import type { Rule } from "./types";

/**
 * Default rules for LaTeX snippet expansion
 */
export const DEFAULT_RULES: Rule[] = [
    { trigger: "\\frac", expand: "\\frac{}{}" },
    { trigger: "\\dfrac", expand: "\\dfrac{}{}" },
    { trigger: "\\tfrac", expand: "\\tfrac{}{}" },
    { trigger: "\\cfrac", expand: "\\cfrac{}{}" },
    { trigger: "\\binom", expand: "\\binom{}{}" },
    { trigger: "\\dbinom", expand: "\\dbinom{}{}" },
    { trigger: "\\tbinom", expand: "\\tbinom{}{}" },
    { trigger: "\\text", expand: "\\text{}" },
    { trigger: "\\sqrt", expand: "\\sqrt{}" },
    { trigger: "\\root", expand: "\\sqrt[]{}" },
    { trigger: "\\sum", expand: "\\sum_{}^{}" },
    { trigger: "\\int", expand: "\\int_{}^{}" },
    { trigger: "\\lim_", expand: "\\lim_{}" },
    { trigger: "\\limsup", expand: "\\limsup_{}" },
    { trigger: "\\liminf", expand: "\\liminf_{}" },
    { trigger: "\\max", expand: "\\max_{}" },
    { trigger: "\\min", expand: "\\min_{}" },
    { trigger: "\\inf_", expand: "\\inf_{}" },
    { trigger: "\\sup", expand: "\\sup_{}" },
    { trigger: "\\log", expand: "\\log_{}" },
    { trigger: "\\pow", expand: "{}^{}" },
    { trigger: "\\abs", expand: "\\left|{}\\right|" },
    { trigger: "\\norm", expand: "\\left\\|{}\\right\\|" },
    { trigger: "\\paren", expand: "\\left({}\\right)" },
    { trigger: "\\brack", expand: "\\left[{}\\right]" },
    { trigger: "\\brace", expand: "\\left\\{{}\\right\\}" },
    { trigger: "\\vec", expand: "\\vec{}" },
    { trigger: "\\hat", expand: "\\hat{}" },
    { trigger: "\\bar", expand: "\\bar{}" },
    { trigger: "\\overline", expand: "\\overline{}" },
    { trigger: "\\underline", expand: "\\underline{}" },
    { trigger: "^^", expand: "^{}" },
    { trigger: "__", expand: "_{}" },
    { trigger: "\\align", expand: "\\begin{align}\n|\n\\end{align}" },
    { trigger: "\\aligned", expand: "\\begin{aligned}\n|\n\\end{aligned}" },
    { trigger: "\\gather", expand: "\\begin{gather}\n|\n\\end{gather}" },
    { trigger: "\\cases", expand: "\\begin{cases}\n|\n\\end{cases}" },
    { trigger: "\\array", expand: "\\begin{array}{}\n|\n\\end{array}" },
    { trigger: "\\matrix", expand: "\\begin{matrix}\n|\n\\end{matrix}" },
    { trigger: "\\pmatrix", expand: "\\begin{pmatrix}\n|\n\\end{pmatrix}" },
    { trigger: "\\bmatrix", expand: "\\begin{bmatrix}\n|\n\\end{bmatrix}" },
    { trigger: "\\vmatrix", expand: "\\begin{vmatrix}\n|\n\\end{vmatrix}" },
    { trigger: "\\Vmatrix", expand: "\\begin{Vmatrix}\n|\n\\end{Vmatrix}" },
    { trigger: "\\smallmatrix", expand: "\\begin{smallmatrix}\n|\n\\end{smallmatrix}" },
    { trigger: "\\split", expand: "\\begin{split}\n|\n\\end{split}" },
    { trigger: "\\multline", expand: "\\begin{multline}\n|\n\\end{multline}" },
    { trigger: "\\alignat", expand: "\\begin{alignat}{}\n\n\\end{alignat}" },
    { trigger: "\\substack", expand: "\\substack{}" },
];
